
title: Corpos Bells

description: > #
baseurl: "" # t
url: ""
address: Rua C-61 • Quadra 133 • Lote 10 • Setor Sudoeste
phone: (62) 3287 - 4164
cellphone: (62) 98192 - 5310
email: corpusbells@hotmail.com
facebook: https://www.facebook.com/magda.bells

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
